### PR TITLE
Fix MS font names

### PR DESCRIPTION
**Pull request by julroy67**
Some of the font names are not matching with the official names and Courier font was missing the "r".

### CODE REVIEW

**Comment by mirkobrombin** [comment]
Fonts are registered with the right name https://github.com/bottlesdevs/dependencies/blob/ad9a36094a2a6ead2b0ce5e360a2ab763f0de553/Fonts/allfonts.yml#L194 the dependency name is based on the executable one

**Comment by mirkobrombin** [comment]
Thanks for your contribution. Description need to be updated in every manifest, not only index.

**Comment by julroy67** [comment]
I already included them in this pull request.
If there are others, could you please indicate me where those are hosted so I can fix them too?

**Comment by mirkobrombin** [comment]
Sorry, I didn't see the other files 😅

**Pull request merged**
