### PR TITLE
Update Mono 9.3.0

### PR DESCRIPTION
**Pull request by jntesteves**
## Type of change
- [ ] New dependency
- [x] Manifest fix
- [ ] Other

# Was this tested using a [local repository](https://maintainers.usebottles.com/Testing)?
- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by Sue1133** [comment]
Version 9.3.0 has already been released.

**Comment by mirkobrombin** [comment]
Missed this one. Anyway a bit out of date now

**Comment by jntesteves** [comment]
> Version 9.3.0 has already been released.

I saw it but didn't have time to test it yet, and I always test Mono on Epic Games Launcher because it's the default dotnet we install for it. I'll update the PR when I get to it.

**Comment by jntesteves** [comment]
I just pushed the update to Mono 9.3.0

**Pull request merged**
