### PR TITLE
Add dotnet461

### PR DESCRIPTION
**Pull request by qogusdn1017**
Haven't tested yet. If there is a method for testing in local, I'll test it and completely start merging.

### CODE REVIEW

**Comment by mirkobrombin** [comment]
To test I have to merge and add it to testing.yml so you have to start Bottles with the env var TESTING_REPOS=1

we are working to improve this

**Comment by qogusdn1017** [comment]
Yup you can proceed! And thank you for answering!

**Comment by qogusdn1017** [comment]
:P
dotnet461

**Comment by mirkobrombin** [comment]
Does it works?

**Comment by qogusdn1017** [comment]
Installation works. However having some issue with mscoree.dll, which was my problem with application using from a few years ago.

Do you have any solutuons about this? I cannot solve it by installing several dotnet packages and everything just goes... crap.

**Comment by mirkobrombin** [comment]
Is mono installed?

**Comment by qogusdn1017** [comment]
Nope, mono is not installed. I'm running with lutris-5.21.

**Pull request merged**
